### PR TITLE
Fix warning code values

### LINKED ISSUE #102: Fix JSON-RPC warning codes to match spec
Per https://www.jsonrpc.org/specification, error codes have to be in [-32000, -32099]. We'd prefer to have our warning codes also respect that.

### PR DESCRIPTION
**Pull request by aasseman**
- Set errors values as [-32000,-32049]
- Set warning values as [-32050, -32099]
- Removing repeating "Error" and "Warning" postfixes.

fixes #102

### CODE REVIEW

File: tap_aggregator/src/error_codes.rs [hunk 1]
```diff
@@ -1,20 +1,35 @@
...
     /// -32002 -- Error during receipt aggregation.
-    AggregationError = -32002,
+    Aggregation = -32002,
 }
 
 /// JSON-RPC warning codes
 /// These are not part of the JSON-RPC spec, but are used to provide additional information to the
 /// client.
 #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
+#[allow(dead_code)]
```
Comment (ColePBryan) [inline tap_aggregator/src/error_codes.rs:28]: Is this `allow` needed? It looks like it is already attached to `Generic` directly. Also since this is public I would think none of it would be considered dead code, although that might just be due to this being a binary instead of a library.

**Review by ColePBryan — CHANGES_REQUESTED** [review]
Just one possible issue here. I'm not sure if we can remove the #[allow(dead_code)] entirely, but at least narrow their scope to the specific variants.

File: tap_aggregator/src/error_codes.rs (hunk 1 above)
Comment (aasseman) [reply tap_aggregator/src/error_codes.rs:28]: Yeah, it was complaining. I'm not using it anywhere (yet?) but still want it as a placeholder for completeness sake

**Review by ColePBryan — APPROVED** [review]

**Comment by aasseman** [comment]
Rebased onto latest main
